-- ============================================================================
-- IntegrateU Workforce Readiness Intelligence
-- 0007_assessment_direct_master_delivery.sql
--
-- PURPOSE
-- Allows employees to take IntegrateU master/template assessments directly
-- without first requiring the company to adopt/copy the role, competencies,
-- and assessment.
--
-- ADDS
--   1. Master-competency scoring support
--   2. Direct master-assessment attempt creation
--   3. 1–4 database-level proficiency enforcement
--   4. Self-service RLS for employees taking their own assessments
--   5. Materialized Technician I assessment questions
--   6. Updated scoring for both template-mode and company-mode assessments
--
-- PRESERVES
--   - Existing company assessment mode
--   - Existing assessment attempts
--   - Existing answer-key security
--   - Existing role/competency structures
-- ============================================================================


-- ============================================================================
-- PART 1 — COMPETENCY SCORES CAN REFERENCE MASTER OR COMPANY COMPETENCIES
-- ============================================================================

alter table competency_scores
add column if not exists master_competency_template_id uuid
references master_competency_templates(id);


alter table competency_scores
alter column competency_id drop not null;


create index if not exists ix_scores_master_competency
on competency_scores(master_competency_template_id);


-- Existing company scores continue using competency_id.
-- New master-assessment scores use master_competency_template_id.
--
-- Exactly one source must be populated.

alter table competency_scores
drop constraint if exists competency_scores_competency_source_check;


alter table competency_scores
add constraint competency_scores_competency_source_check
check (
  (
    competency_id is not null
    and master_competency_template_id is null
  )
  or
  (
    competency_id is null
    and master_competency_template_id is not null
  )
);


-- One master competency score per attempt.

create unique index if not exists uq_scores_attempt_master_competency
on competency_scores (
  attempt_id,
  master_competency_template_id
)
where master_competency_template_id is not null;



-- ============================================================================
-- PART 2 — ENFORCE THE INTEGRATEU 1–4 PROFICIENCY SCALE
-- ============================================================================

-- Historical scores generated by the old 1–5 algorithm may contain Level 5.
-- Under the approved IntegrateU scale, Level 4 is the maximum.

update competency_scores
set estimated_level = 4
where estimated_level > 4;


alter table competency_scores
drop constraint if exists competency_scores_estimated_level_check;


alter table competency_scores
add constraint competency_scores_estimated_level_check
check (
  estimated_level between 1 and 4
);



-- ============================================================================
-- PART 3 — EMPLOYEE SELF-SERVICE RLS
--
-- Company admins and IntegrateU admins retain their existing access.
-- Employees may now access their OWN attempt records/results.
-- ============================================================================


-- --------------------------------------------------------------------------
-- assessment_attempts
-- --------------------------------------------------------------------------

drop policy if exists attempts_all
on assessment_attempts;


create policy attempts_all
on assessment_attempts
for all

using (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (
    select 1
    from employees e
    where e.id = assessment_attempts.employee_id
      and e.auth_user_id = auth.uid()
  )

)

with check (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (
    select 1
    from employees e
    where e.id = assessment_attempts.employee_id
      and e.auth_user_id = auth.uid()
  )

);



-- --------------------------------------------------------------------------
-- attempt_answers
-- --------------------------------------------------------------------------

drop policy if exists answers_all
on attempt_answers;


create policy answers_all
on attempt_answers
for all

using (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (

    select 1

    from assessment_attempts a

    join employees e
      on e.id = a.employee_id

    where a.id = attempt_answers.attempt_id
      and e.auth_user_id = auth.uid()

  )

)

with check (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (

    select 1

    from assessment_attempts a

    join employees e
      on e.id = a.employee_id

    where a.id = attempt_answers.attempt_id
      and e.auth_user_id = auth.uid()

  )

);



-- --------------------------------------------------------------------------
-- attempt_question_selections
-- --------------------------------------------------------------------------

drop policy if exists attempt_question_all
on attempt_question_selections;


create policy attempt_question_all
on attempt_question_selections
for all

using (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (

    select 1

    from assessment_attempts a

    join employees e
      on e.id = a.employee_id

    where a.id = attempt_question_selections.attempt_id
      and e.auth_user_id = auth.uid()

  )

)

with check (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (

    select 1

    from assessment_attempts a

    join employees e
      on e.id = a.employee_id

    where a.id = attempt_question_selections.attempt_id
      and e.auth_user_id = auth.uid()

  )

);



-- --------------------------------------------------------------------------
-- competency_scores
-- --------------------------------------------------------------------------

drop policy if exists scores_all
on competency_scores;


create policy scores_all
on competency_scores
for all

using (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (
    select 1
    from employees e
    where e.id = competency_scores.employee_id
      and e.auth_user_id = auth.uid()
  )

)

with check (

  wri_is_integrateu_admin()

  or client_id in (
    select wri_allowed_client_ids()
  )

  or exists (
    select 1
    from employees e
    where e.id = competency_scores.employee_id
      and e.auth_user_id = auth.uid()
  )

);



-- ============================================================================
-- PART 4 — MATERIALIZE THE 100 TECHNICIAN I MASTER QUESTIONS
--
-- The Master Question Bank remains the reusable source.
--
-- assessment_questions is the stable assessment-specific snapshot used by
-- attempts. Future edits/versioning in the Master Question Bank therefore
-- do not silently change an already-built assessment.
-- ============================================================================

do $$
declare

  v_industry_id uuid;
  v_role_template_id uuid;
  v_assessment_id uuid;

  v_master_question record;

  v_assessment_question_id uuid;

  v_sort_order int := 0;

  v_materialized_count int;
  v_answer_key_count int;

begin


  -- --------------------------------------------------------------------------
  -- Resolve CI industry
  -- --------------------------------------------------------------------------

  select id
  into v_industry_id

  from industries

  where lower(slug) = 'ci'
     or lower(name) = 'custom integration'

  order by
    case
      when lower(slug) = 'ci' then 0
      else 1
    end

  limit 1;


  if v_industry_id is null then
    raise exception
      'Custom Integration industry not found';
  end if;



  -- --------------------------------------------------------------------------
  -- Resolve Technician I master role
  -- --------------------------------------------------------------------------

  select id
  into v_role_template_id

  from master_role_templates

  where industry_id = v_industry_id
    and name = 'Technician I — Entry Level'
    and is_current = true

  order by version desc

  limit 1;


  if v_role_template_id is null then
    raise exception
      'Technician I — Entry Level master role template not found';
  end if;



  -- --------------------------------------------------------------------------
  -- Resolve Technician I master assessment
  -- --------------------------------------------------------------------------

  select id
  into v_assessment_id

  from assessments

  where client_id is null
    and industry_id = v_industry_id
    and name = 'Technician I — Entry Level Pre-Assessment'
    and is_current = true

  order by version desc

  limit 1;


  if v_assessment_id is null then
    raise exception
      'Technician I — Entry Level Pre-Assessment not found';
  end if;



  -- --------------------------------------------------------------------------
  -- Copy all approved Technician I Master Questions into assessment_questions
  -- --------------------------------------------------------------------------

  for v_master_question in

    select
      q.*,
      k.correct_answer,
      k.scoring_notes,
      k.rationale

    from master_question_bank q

    join master_question_role_applicability ra
      on ra.master_question_id = q.id

    join master_question_answer_keys k
      on k.master_question_id = q.id

    where q.industry_id = v_industry_id
      and q.is_current = true
      and q.status = 'approved'
      and ra.master_role_template_id = v_role_template_id

    order by
      q.domain,
      q.created_at,
      q.id

  loop


    v_sort_order := v_sort_order + 1;


    -- Reuse an existing snapshot if this Master Question was already copied.

    select id
    into v_assessment_question_id

    from assessment_questions

    where assessment_id = v_assessment_id
      and source_master_question_id = v_master_question.id

    limit 1;



    if v_assessment_question_id is null then


      insert into assessment_questions (

        assessment_id,
        master_competency_template_id,

        type,
        prompt,
        scenario,
        image_url,
        options,
        points,
        sort_order,

        source_master_question_id,
        domain,
        difficulty,

        critical_safety,
        practical_verification_required

      )

      values (

        v_assessment_id,
        v_master_question.master_competency_template_id,

        v_master_question.type,
        v_master_question.prompt,
        v_master_question.scenario,
        v_master_question.image_url,
        v_master_question.options,
        v_master_question.points,
        v_sort_order,

        v_master_question.id,
        v_master_question.domain,
        v_master_question.difficulty,

        v_master_question.critical_safety,
        v_master_question.practical_verification_required

      )

      returning id
      into v_assessment_question_id;


    end if;



    -- ------------------------------------------------------------------------
    -- Copy secure answer key into the assessment-specific answer-key table.
    -- ------------------------------------------------------------------------

    insert into assessment_question_answer_keys (

      question_id,
      correct_answer,
      scoring_notes

    )

    select

      v_assessment_question_id,

      v_master_question.correct_answer,

      concat_ws(

        E'\n\n',

        v_master_question.scoring_notes,

        case

          when v_master_question.rationale is not null

          then
            'Rationale: '
            || v_master_question.rationale

          else null

        end

      )

    where not exists (

      select 1

      from assessment_question_answer_keys existing_key

      where existing_key.question_id =
        v_assessment_question_id

    );


  end loop;



  -- --------------------------------------------------------------------------
  -- Verify exactly 100 seeded master-question snapshots exist.
  -- --------------------------------------------------------------------------

  select count(*)
  into v_materialized_count

  from assessment_questions

  where assessment_id = v_assessment_id
    and source_master_question_id is not null;



  if v_materialized_count <> 100 then

    raise exception
      'Technician I assessment expected 100 materialized Master Questions; found %',
      v_materialized_count;

  end if;



  -- --------------------------------------------------------------------------
  -- Verify all 100 have answer keys.
  -- --------------------------------------------------------------------------

  select count(*)
  into v_answer_key_count

  from assessment_question_answer_keys k

  join assessment_questions q
    on q.id = k.question_id

  where q.assessment_id = v_assessment_id
    and q.source_master_question_id is not null;



  if v_answer_key_count <> 100 then

    raise exception
      'Technician I assessment expected 100 answer keys; found %',
      v_answer_key_count;

  end if;


end;
$$;



-- ============================================================================
-- PART 5 — START / RESUME A DIRECT MASTER ASSESSMENT
--
-- Returns the attempt id.
--
-- Authorized callers:
--   IntegrateU admin
--   Client admin for the employee's client
--   The employee themself
--
-- Question selection follows assessment_blueprint_rules.
-- ============================================================================

create or replace function wri_start_master_assessment(

  p_employee_id uuid,
  p_assessment_id uuid

)

returns uuid

language plpgsql

security definer

set search_path = public

as $$

declare

  v_employee employees;
  v_assessment assessments;

  v_attempt_id uuid;
  v_existing_attempt_id uuid;

  v_rule record;
  v_question record;

  v_order int := 0;

  v_expected_count int;
  v_selected_count int;
  v_answer_key_count int;

begin


  -- --------------------------------------------------------------------------
  -- Employee
  -- --------------------------------------------------------------------------

  select *
  into v_employee

  from employees

  where id = p_employee_id;


  if v_employee is null then
    raise exception
      'employee % not found',
      p_employee_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Authorization
  -- --------------------------------------------------------------------------

  if not (

    wri_is_integrateu_admin()

    or v_employee.client_id in (
      select wri_allowed_client_ids()
    )

    or v_employee.auth_user_id = auth.uid()

  ) then

    raise exception
      'not authorized to start assessment for employee %',
      p_employee_id;

  end if;



  -- --------------------------------------------------------------------------
  -- Assessment
  -- --------------------------------------------------------------------------

  select *
  into v_assessment

  from assessments

  where id = p_assessment_id;


  if v_assessment is null then
    raise exception
      'assessment % not found',
      p_assessment_id;
  end if;


  if v_assessment.client_id is not null then
    raise exception
      'wri_start_master_assessment only accepts template-mode assessments';
  end if;


  if not v_assessment.is_current then
    raise exception
      'assessment % is not the current published version',
      p_assessment_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Resume existing unfinished attempt rather than create duplicates.
  -- --------------------------------------------------------------------------

  select id
  into v_existing_attempt_id

  from assessment_attempts

  where employee_id = p_employee_id
    and assessment_id = p_assessment_id
    and status in (
      'not_started',
      'in_progress'
    )

  order by created_at desc

  limit 1;


  if v_existing_attempt_id is not null then
    return v_existing_attempt_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Create attempt.
  --
  -- client_id is populated from the employee by the existing sync trigger.
  -- role_id remains NULL because the attempt measures the IntegrateU
  -- MASTER role standard directly.
  -- --------------------------------------------------------------------------

  insert into assessment_attempts (

    client_id,
    employee_id,
    assessment_id,
    role_id,

    status,
    started_at,
    created_by

  )

  values (

    v_employee.client_id,
    p_employee_id,
    p_assessment_id,
    null,

    'in_progress',
    now(),
    auth.uid()

  )

  returning id
  into v_attempt_id;



  -- --------------------------------------------------------------------------
  -- Expected total from blueprint.
  -- --------------------------------------------------------------------------

  select coalesce(
    sum(question_count),
    0
  )

  into v_expected_count

  from assessment_blueprint_rules

  where assessment_id = p_assessment_id;


  if v_expected_count = 0 then
    raise exception
      'assessment % has no blueprint rules',
      p_assessment_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Build randomized question snapshot using domain + difficulty counts.
  -- --------------------------------------------------------------------------

  for v_rule in

    select *

    from assessment_blueprint_rules

    where assessment_id = p_assessment_id

    order by sort_order, id

  loop


    -- ------------------------------------------------------------------------
    -- FOUNDATIONAL
    -- ------------------------------------------------------------------------

    for v_question in

      select q.id

      from assessment_questions q

      where q.assessment_id = p_assessment_id
        and q.domain = v_rule.domain
        and q.difficulty = 'foundational'
        and q.source_master_question_id is not null

      order by random()

      limit v_rule.foundational_count

    loop

      v_order := v_order + 1;


      insert into attempt_question_selections (

        client_id,
        attempt_id,
        question_id,
        question_order

      )

      values (

        v_employee.client_id,
        v_attempt_id,
        v_question.id,
        v_order

      );

    end loop;



    -- ------------------------------------------------------------------------
    -- APPLICATION
    -- ------------------------------------------------------------------------

    for v_question in

      select q.id

      from assessment_questions q

      where q.assessment_id = p_assessment_id
        and q.domain = v_rule.domain
        and q.difficulty = 'application'
        and q.source_master_question_id is not null

      order by random()

      limit v_rule.application_count

    loop

      v_order := v_order + 1;


      insert into attempt_question_selections (

        client_id,
        attempt_id,
        question_id,
        question_order

      )

      values (

        v_employee.client_id,
        v_attempt_id,
        v_question.id,
        v_order

      );

    end loop;



    -- ------------------------------------------------------------------------
    -- SCENARIO
    -- ------------------------------------------------------------------------

    for v_question in

      select q.id

      from assessment_questions q

      where q.assessment_id = p_assessment_id
        and q.domain = v_rule.domain
        and q.difficulty = 'scenario'
        and q.source_master_question_id is not null

      order by random()

      limit v_rule.scenario_count

    loop

      v_order := v_order + 1;


      insert into attempt_question_selections (

        client_id,
        attempt_id,
        question_id,
        question_order

      )

      values (

        v_employee.client_id,
        v_attempt_id,
        v_question.id,
        v_order

      );

    end loop;


  end loop;



  -- --------------------------------------------------------------------------
  -- Validate selection count.
  -- --------------------------------------------------------------------------

  select count(*)
  into v_selected_count

  from attempt_question_selections

  where attempt_id = v_attempt_id;


  if v_selected_count <> v_expected_count then

    raise exception
      'assessment blueprint expected % questions but only % could be selected',
      v_expected_count,
      v_selected_count;

  end if;



  -- --------------------------------------------------------------------------
  -- Validate selected questions all have secure answer keys.
  -- --------------------------------------------------------------------------

  select count(*)

  into v_answer_key_count

  from attempt_question_selections aqs

  join assessment_question_answer_keys k
    on k.question_id = aqs.question_id

  where aqs.attempt_id = v_attempt_id;


  if v_answer_key_count <> v_selected_count then

    raise exception
      'attempt % contains selected questions without answer keys',
      v_attempt_id;

  end if;



  return v_attempt_id;


end;
$$;


revoke all
on function wri_start_master_assessment(uuid, uuid)
from public, anon;


grant execute
on function wri_start_master_assessment(uuid, uuid)
to authenticated;



-- ============================================================================
-- PART 6 — SCORING V3
--
-- Supports BOTH:
--
--   TEMPLATE / MASTER ASSESSMENT
--     q.master_competency_template_id
--     master_role_competency_requirements
--
--   COMPANY ASSESSMENT
--     q.competency_id
--     role_competency_requirements
--
-- Answer comparison remains server-side and secure.
-- ============================================================================

create or replace function wri_score_attempt(

  p_attempt_id uuid

)

returns void

language plpgsql

security definer

set search_path = public

as $$

declare

  v_attempt assessment_attempts;
  v_assessment assessments;

  v_employee_auth_user_id uuid;

  v_selected_question_count int;
  v_answered_question_count int;

  v_master_role_template_id uuid;
  v_company_role_id uuid;

begin


  -- --------------------------------------------------------------------------
  -- Attempt
  -- --------------------------------------------------------------------------

  select *
  into v_attempt

  from assessment_attempts

  where id = p_attempt_id;


  if v_attempt is null then
    raise exception
      'attempt % not found',
      p_attempt_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Assessment
  -- --------------------------------------------------------------------------

  select *
  into v_assessment

  from assessments

  where id = v_attempt.assessment_id;


  if v_assessment is null then
    raise exception
      'assessment for attempt % not found',
      p_attempt_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Authorization
  -- --------------------------------------------------------------------------

  select auth_user_id
  into v_employee_auth_user_id

  from employees

  where id = v_attempt.employee_id;


  if not (

    wri_is_integrateu_admin()

    or v_attempt.client_id in (
      select wri_allowed_client_ids()
    )

    or v_employee_auth_user_id = auth.uid()

  ) then

    raise exception
      'not authorized to score attempt %',
      p_attempt_id;

  end if;



  if v_attempt.status = 'completed' then
    raise exception
      'attempt % already scored',
      p_attempt_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Validate question snapshot.
  -- --------------------------------------------------------------------------

  select count(*)
  into v_selected_question_count

  from attempt_question_selections

  where attempt_id = p_attempt_id;


  if v_selected_question_count = 0 then
    raise exception
      'attempt % has no selected questions',
      p_attempt_id;
  end if;



  -- --------------------------------------------------------------------------
  -- Require every selected question to have an answer.
  -- --------------------------------------------------------------------------

  select count(*)
  into v_answered_question_count

  from attempt_answers aa

  join attempt_question_selections aqs
    on aqs.attempt_id = aa.attempt_id
   and aqs.question_id = aa.question_id

  where aa.attempt_id = p_attempt_id;


  if v_answered_question_count <> v_selected_question_count then

    raise exception
      'attempt % is incomplete: % of % selected questions answered',
      p_attempt_id,
      v_answered_question_count,
      v_selected_question_count;

  end if;



  -- --------------------------------------------------------------------------
  -- Secure answer comparison.
  -- --------------------------------------------------------------------------

  update attempt_answers aa

  set is_correct = (

    select

      case

        when jsonb_typeof(k.correct_answer) = 'array'

        then (

          select array_agg(x order by x)

          from jsonb_array_elements_text(
            k.correct_answer
          ) x

        ) = (

          select array_agg(y order by y)

          from jsonb_array_elements_text(
            aa.response
          ) y

        )

        else

          k.correct_answer = aa.response

      end

    from assessment_question_answer_keys k

    where k.question_id = aa.question_id

  )

  where aa.attempt_id = p_attempt_id;



  -- --------------------------------------------------------------------------
  -- No missing answer keys allowed.
  -- --------------------------------------------------------------------------

  if exists (

    select 1

    from attempt_answers

    where attempt_id = p_attempt_id
      and is_correct is null

  ) then

    raise exception
      'attempt % contains one or more questions without a valid answer key',
      p_attempt_id;

  end if;



  -- --------------------------------------------------------------------------
  -- Remove any partial/pre-existing scoring rows for this unfinished attempt.
  -- --------------------------------------------------------------------------

  delete from competency_scores

  where attempt_id = p_attempt_id;



  -- ==========================================================================
  -- TEMPLATE / MASTER ASSESSMENT
  -- ==========================================================================

  if v_assessment.client_id is null then


    v_master_role_template_id :=
      coalesce(
        v_assessment.master_target_role_template_id,
        v_assessment.master_role_template_id
      );


    if v_master_role_template_id is null then
      raise exception
        'template assessment % has no master role template',
        v_assessment.id;
    end if;



    insert into competency_scores (

      client_id,
      attempt_id,
      employee_id,

      competency_id,
      master_competency_template_id,

      score_percent,
      estimated_level,
      required_level

    )

    select

      v_attempt.client_id,
      p_attempt_id,
      v_attempt.employee_id,

      null,
      q.master_competency_template_id,

      round(

        100.0

        * sum(

            case
              when aa.is_correct
              then q.points
              else 0
            end

          )

        / nullif(
            sum(q.points),
            0
          ),

        1

      ),


      least(

        4,

        greatest(

          1,

          ceil(

            4.0

            * sum(

                case
                  when aa.is_correct
                  then q.points
                  else 0
                end

              )

            / nullif(
                sum(q.points),
                0
              )

          )::int

        )

      ),


      mrcr.required_level


    from attempt_answers aa


    join attempt_question_selections aqs

      on aqs.attempt_id = aa.attempt_id

     and aqs.question_id = aa.question_id


    join assessment_questions q

      on q.id = aa.question_id


    left join master_role_competency_requirements mrcr

      on mrcr.master_role_template_id =
        v_master_role_template_id

     and mrcr.master_competency_template_id =
        q.master_competency_template_id


    where aa.attempt_id = p_attempt_id

      and q.master_competency_template_id
        is not null


    group by

      q.master_competency_template_id,
      mrcr.required_level;



  -- ==========================================================================
  -- COMPANY ASSESSMENT
  -- ==========================================================================

  else


    v_company_role_id :=
      coalesce(

        v_attempt.role_id,
        v_assessment.target_role_id,
        v_assessment.role_id

      );


    insert into competency_scores (

      client_id,
      attempt_id,
      employee_id,

      competency_id,
      master_competency_template_id,

      score_percent,
      estimated_level,
      required_level

    )

    select

      v_attempt.client_id,
      p_attempt_id,
      v_attempt.employee_id,

      q.competency_id,
      null,

      round(

        100.0

        * sum(

            case
              when aa.is_correct
              then q.points
              else 0
            end

          )

        / nullif(
            sum(q.points),
            0
          ),

        1

      ),


      least(

        4,

        greatest(

          1,

          ceil(

            4.0

            * sum(

                case
                  when aa.is_correct
                  then q.points
                  else 0
                end

              )

            / nullif(
                sum(q.points),
                0
              )

          )::int

        )

      ),


      rcr.required_level


    from attempt_answers aa


    join attempt_question_selections aqs

      on aqs.attempt_id = aa.attempt_id

     and aqs.question_id = aa.question_id


    join assessment_questions q

      on q.id = aa.question_id


    left join role_competency_requirements rcr

      on rcr.role_id = v_company_role_id

     and rcr.competency_id =
        q.competency_id


    where aa.attempt_id = p_attempt_id

      and q.competency_id is not null


    group by

      q.competency_id,
      rcr.required_level;


  end if;



  -- --------------------------------------------------------------------------
  -- Complete attempt.
  -- --------------------------------------------------------------------------

  update assessment_attempts

  set

    status = 'completed',
    completed_at = now(),
    updated_at = now()

  where id = p_attempt_id;


end;
$$;


revoke all
on function wri_score_attempt(uuid)
from public, anon;


grant execute
on function wri_score_attempt(uuid)
to authenticated;



-- ============================================================================
-- PART 7 — VERIFICATION
-- ============================================================================

with tech_assessment as (

  select id, name

  from assessments

  where client_id is null
    and name = 'Technician I — Entry Level Pre-Assessment'
    and is_current = true

  order by version desc

  limit 1

),

question_counts as (

  select
    q.assessment_id,
    count(*) as materialized_questions

  from assessment_questions q

  where q.source_master_question_id is not null

  group by q.assessment_id

),

answer_key_counts as (

  select
    q.assessment_id,
    count(*) as secure_answer_keys

  from assessment_questions q

  join assessment_question_answer_keys k
    on k.question_id = q.id

  where q.source_master_question_id is not null

  group by q.assessment_id

),

blueprint_counts as (

  select
    b.assessment_id,
    count(*) as blueprint_rules,
    sum(b.question_count) as blueprint_question_total

  from assessment_blueprint_rules b

  group by b.assessment_id

)

select

  a.name as assessment,

  coalesce(
    q.materialized_questions,
    0
  ) as materialized_questions,

  coalesce(
    k.secure_answer_keys,
    0
  ) as secure_answer_keys,

  coalesce(
    b.blueprint_rules,
    0
  ) as blueprint_rules,

  coalesce(
    b.blueprint_question_total,
    0
  ) as blueprint_question_total

from tech_assessment a

left join question_counts q
  on q.assessment_id = a.id

left join answer_key_counts k
  on k.assessment_id = a.id

left join blueprint_counts b
  on b.assessment_id = a.id;