-- ============================================================================
-- 0057_role_development_activity_competency_link.sql
--
-- Gives role-development activities a durable structured relationship to the
-- master competency and target requirement that created them.
--
-- This allows activities to launch evidence workflows without parsing titles.
--
-- Fields:
--   master_competency_template_id
--   target_required_level_snapshot
--   target_status_snapshot
--
-- Existing generated role-comparison activities are backfilled only when an
-- exact generated title matches a competency required by that plan's target
-- master role.
-- ============================================================================


-- ============================================================================
-- PART 1 — STRUCTURED ACTIVITY LINKAGE
-- ============================================================================

alter table public.development_plan_activities
  add column if not exists
  master_competency_template_id uuid
  references public.master_competency_templates(id)
  on delete set null;


alter table public.development_plan_activities
  add column if not exists
  target_required_level_snapshot integer;


alter table public.development_plan_activities
  add column if not exists
  target_status_snapshot text;


alter table public.development_plan_activities
  drop constraint if exists
  development_plan_activities_target_level_check;

alter table public.development_plan_activities
  add constraint
  development_plan_activities_target_level_check
  check (
    target_required_level_snapshot is null
    or target_required_level_snapshot between 1 and 5
  );


alter table public.development_plan_activities
  drop constraint if exists
  development_plan_activities_target_status_check;

alter table public.development_plan_activities
  add constraint
  development_plan_activities_target_status_check
  check (
    target_status_snapshot is null
    or target_status_snapshot in (
      'knowledge_gap',
      'practical_gap',
      'not_assessed',
      'reverification_due',
      'reverification_required',
      'ready'
    )
  );


create index if not exists
development_plan_activities_master_competency_idx
on public.development_plan_activities(
  master_competency_template_id
);


-- ============================================================================
-- PART 2 — BACKFILL EXISTING GENERATED ROLE-DEVELOPMENT ACTIVITIES
--
-- We do NOT parse arbitrary titles.
--
-- A candidate must:
--   1. belong to a role_comparison plan
--   2. reference a competency actually required by that target role
--   3. exactly equal one of the titles generated by 0055
--
-- Only uniquely matched activities are updated.
-- ============================================================================

with candidate_matches as (

  select
    a.id as activity_id,

    mrcr.master_competency_template_id,

    mrcr.required_level
      as target_required_level_snapshot,

    case

      when a.title =
        'Build target-role knowledge — ' ||
        mct.name
        then 'knowledge_gap'

      when a.title =
        'Develop target-role practical proficiency — ' ||
        mct.name
        then 'practical_gap'

      when a.title =
        'Assess target-role competency — ' ||
        mct.name
        then 'not_assessed'

      when a.title =
        'Refresh practical verification — ' ||
        mct.name
        then 'reverification_due'

      when a.title =
        'Reverify target-role competency — ' ||
        mct.name
        then 'reverification_required'

      when a.title =
        'Develop target-role competency — ' ||
        mct.name
        then 'ready'

      else null

    end as target_status_snapshot

  from public.development_plan_activities a

  join public.development_plans dp
    on dp.id =
       a.development_plan_id

  join public.master_role_competency_requirements mrcr
    on mrcr.master_role_template_id =
       dp.target_master_role_template_id

  join public.master_competency_templates mct
    on mct.id =
       mrcr.master_competency_template_id

  where dp.origin =
    'role_comparison'

    and a.master_competency_template_id
      is null

    and (

      a.title =
        'Build target-role knowledge — ' ||
        mct.name

      or a.title =
        'Develop target-role practical proficiency — ' ||
        mct.name

      or a.title =
        'Assess target-role competency — ' ||
        mct.name

      or a.title =
        'Refresh practical verification — ' ||
        mct.name

      or a.title =
        'Reverify target-role competency — ' ||
        mct.name

      or a.title =
        'Develop target-role competency — ' ||
        mct.name

    )

),

unique_matches as (

  select
    activity_id,

    (array_agg(
      master_competency_template_id
    ))[1]
      as master_competency_template_id,

    (array_agg(
      target_required_level_snapshot
    ))[1]
      as target_required_level_snapshot,

    (array_agg(
      target_status_snapshot
    ))[1]
      as target_status_snapshot

  from candidate_matches

  group by activity_id

  having count(*) = 1

)

update public.development_plan_activities a

set
  master_competency_template_id =
    m.master_competency_template_id,

  target_required_level_snapshot =
    m.target_required_level_snapshot,

  target_status_snapshot =
    m.target_status_snapshot

from unique_matches m

where a.id =
  m.activity_id;


-- ============================================================================
-- PART 3 — FAIL LOUDLY IF A GENERATED ACTIVITY COULD NOT BE LINKED
--
-- Manual activities are allowed to remain unlinked.
-- Only titles matching the known 0055 generated patterns are validated here.
-- ============================================================================

do $block$

declare
  v_unlinked_count integer;

begin

  select count(*)

  into v_unlinked_count

  from public.development_plan_activities a

  join public.development_plans dp
    on dp.id =
       a.development_plan_id

  where dp.origin =
    'role_comparison'

    and a.master_competency_template_id
      is null

    and (

      a.title like
        'Build target-role knowledge — %'

      or a.title like
        'Develop target-role practical proficiency — %'

      or a.title like
        'Assess target-role competency — %'

      or a.title like
        'Refresh practical verification — %'

      or a.title like
        'Reverify target-role competency — %'

      or a.title like
        'Develop target-role competency — %'

    );


  if v_unlinked_count > 0 then

    raise exception
      '% generated role-development activity record(s) could not be uniquely linked to a target-role competency',
      v_unlinked_count;

  end if;

end;

$block$;


comment on column
public.development_plan_activities.master_competency_template_id
is
'Master competency directly associated with this activity when the work is competency-specific.';


comment on column
public.development_plan_activities.target_required_level_snapshot
is
'Target master-role required level captured when a role-development activity is generated.';


comment on column
public.development_plan_activities.target_status_snapshot
is
'Target-role comparison status captured when a role-development activity is generated.';


-- ============================================================================
-- PART 4 — UPDATE ROLE-COMPARISON PLAN GENERATOR
--
-- Same generator as 0055, now persisting structured competency context on each
-- generated activity.
-- ============================================================================

create or replace function
public.wri_create_role_comparison_development_plan(
  p_employee_id uuid,
  p_target_role_template_id uuid,
  p_due_date date default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $function$

declare
  v_client_id uuid;
  v_target_role_name text;
  v_current_role_name text;
  v_existing_plan_id uuid;
  v_plan_id uuid;
  v_need_count integer;
begin

  -- --------------------------------------------------------------------------
  -- Employee
  -- --------------------------------------------------------------------------

  select
    e.client_id
  into
    v_client_id
  from public.employees e
  where e.id = p_employee_id;

  if v_client_id is null then
    raise exception
      'employee % was not found',
      p_employee_id;
  end if;


  -- --------------------------------------------------------------------------
  -- Authorization
  --
  -- Role-development plans are management actions.
  -- --------------------------------------------------------------------------

  if not (
    public.wri_is_integrateu_admin()
    or v_client_id in (
      select
        public.wri_allowed_client_ids()
    )
  ) then
    raise exception
      'not authorized to create a role development plan for employee %',
      p_employee_id;
  end if;


  -- --------------------------------------------------------------------------
  -- Target role
  -- --------------------------------------------------------------------------

  select
    mrt.name
  into
    v_target_role_name
  from public.master_role_templates mrt
  where
    mrt.id =
      p_target_role_template_id
    and mrt.is_current = true
    and mrt.status = 'active';

  if v_target_role_name is null then
    raise exception
      'target master role % is not a current active role',
      p_target_role_template_id;
  end if;


  -- --------------------------------------------------------------------------
  -- Existing unresolved plan
  --
  -- Creation is idempotent for employee + target role.
  -- --------------------------------------------------------------------------

  select
    dp.id
  into
    v_existing_plan_id
  from public.development_plans dp
  where
    dp.employee_id =
      p_employee_id
    and dp.origin =
      'role_comparison'
    and dp.target_master_role_template_id =
      p_target_role_template_id
    and dp.resolution_status not in (
      'resolved',
      'cancelled'
    )
  order by
    dp.created_at desc
  limit 1;

  if v_existing_plan_id is not null then
    return v_existing_plan_id;
  end if;


  -- --------------------------------------------------------------------------
  -- Evaluate target role using the canonical comparison engine.
  -- --------------------------------------------------------------------------

  select
    count(*)
  into
    v_need_count
  from public.wri_compare_employee_role_readiness(
    p_employee_id,
    p_target_role_template_id
  ) comparison
  where comparison.target_status <>
    'ready';

  if coalesce(v_need_count, 0) = 0 then
    raise exception
      'employee already meets all requirements for target role %',
      v_target_role_name;
  end if;


  select
    comparison.current_role_name
  into
    v_current_role_name
  from public.wri_compare_employee_role_readiness(
    p_employee_id,
    p_target_role_template_id
  ) comparison
  limit 1;


  -- --------------------------------------------------------------------------
  -- Create parent plan.
  --
  -- action_key remains NULL by design:
  -- this must not appear as a current-readiness action.
  -- --------------------------------------------------------------------------

  insert into public.development_plans (
    client_id,
    employee_id,

    attempt_id,

    created_by,
    created_by_user_id,

    action_key,
    action_type,
    action_label,

    master_competency_template_id,
    competency_name_snapshot,

    role_name_snapshot,

    title,
    description,

    development_type,
    status,
    priority,

    start_date,
    due_date,

    owner_user_id,

    resolution_status,

    origin,

    target_master_role_template_id,
    target_role_name_snapshot
  )
  values (
    v_client_id,
    p_employee_id,

    null,

    auth.uid(),
    auth.uid(),

    null,
    null,
    'Role Development',

    null,
    null,

    v_current_role_name,

    'Role Development — ' ||
      v_target_role_name,

    'Development plan generated from role-readiness comparison. ' ||
    'This plan supports development toward ' ||
    v_target_role_name ||
    ' and does not change current-role readiness.',

    'other',
    'not_started',
    'medium',

    current_date,
    p_due_date,

    null,

    'development_in_progress',

    'role_comparison',

    p_target_role_template_id,
    v_target_role_name
  )
  returning id
  into v_plan_id;


  -- --------------------------------------------------------------------------
  -- Generate activities from every target-role requirement that is not ready.
  -- --------------------------------------------------------------------------

  insert into public.development_plan_activities (
    development_plan_id,
    client_id,
    employee_id,

    master_competency_template_id,
    target_required_level_snapshot,
    target_status_snapshot,

    title,
    description,

    activity_type,
    status,
    sequence_number,

    due_date,

    created_by_user_id
  )
  select
    v_plan_id,
    v_client_id,
    p_employee_id,

    comparison.master_competency_template_id,
    comparison.target_required_level,
    comparison.target_status,

    case comparison.target_status

      when 'knowledge_gap'
        then
          'Build target-role knowledge — ' ||
          comparison.competency_name

      when 'practical_gap'
        then
          'Develop target-role practical proficiency — ' ||
          comparison.competency_name

      when 'not_assessed'
        then
          'Assess target-role competency — ' ||
          comparison.competency_name

      when 'reverification_due'
        then
          'Refresh practical verification — ' ||
          comparison.competency_name

      when 'reverification_required'
        then
          'Reverify target-role competency — ' ||
          comparison.competency_name

      else
        'Develop target-role competency — ' ||
        comparison.competency_name

    end as title,


    case comparison.target_status

      when 'knowledge_gap'
        then concat(
          'Current knowledge level: ',
          coalesce(
            comparison.current_knowledge_level::text,
            'not assessed'
          ),
          '. Target role requires Level ',
          comparison.target_required_level,
          '.'
        )

      when 'practical_gap'
        then concat(
          'Current practical level: ',
          coalesce(
            comparison.current_practical_level::text,
            'not verified'
          ),
          '. Target role requires Level ',
          comparison.target_required_level,
          '. Knowledge currently meets the target requirement.'
        )

      when 'not_assessed'
        then concat(
          'No current knowledge evidence is available for this competency. ',
          'Target role requires Level ',
          comparison.target_required_level,
          '.'
        )

      when 'reverification_due'
        then concat(
          'Existing practical evidence meets the target level but is due for ',
          'reverification. Target role requires Level ',
          comparison.target_required_level,
          '.'
        )

      when 'reverification_required'
        then concat(
          'Existing practical evidence has expired and must be renewed. ',
          'Target role requires Level ',
          comparison.target_required_level,
          '.'
        )

      else
        concat(
          'Target role requires Level ',
          comparison.target_required_level,
          '.'
        )

    end as description,


    case comparison.target_status

      when 'knowledge_gap'
        then 'training'

      when 'practical_gap'
        then 'field_practice'

      when 'reverification_due'
        then 'practical_verification'

      when 'reverification_required'
        then 'practical_verification'

      when 'not_assessed'
        then 'other'

      else
        'other'

    end as activity_type,


    'not_started',

    row_number() over (
      order by
        case comparison.target_status
          when 'reverification_required' then 1
          when 'knowledge_gap' then 2
          when 'practical_gap' then 3
          when 'reverification_due' then 4
          when 'not_assessed' then 5
          else 6
        end,
        comparison.competency_name
    )::integer,

    p_due_date,

    auth.uid()

  from public.wri_compare_employee_role_readiness(
    p_employee_id,
    p_target_role_template_id
  ) comparison

  where comparison.target_status <>
    'ready';


  -- --------------------------------------------------------------------------
  -- Re-run existing lifecycle calculation after the generated activities exist.
  -- --------------------------------------------------------------------------

  perform
    public.wri_refresh_development_plan_status(
      v_plan_id
    );

  perform
    public.wri_refresh_development_plan_resolution(
      v_plan_id
    );


  return v_plan_id;

end;

$function$;
