-- ============================================================================
-- IntegrateU Workforce Readiness Intelligence
-- 0122_financial_literacy_production_question_bank.sql
--
-- Production Master Question Banks:
--   Competency: Financial Literacy
--   Level 1: 20 questions = 8 foundational / 8 application / 4 scenario
--
-- Roles:
--   Construction Worker -> Level 1
--
-- Each target level receives its own current assessment family.
-- Existing exact-prompt Master Questions and source-linked snapshots are reused.
--
-- Safety note: these questions assess safe-work judgment and hazard recognition.
-- They do not replace employer-specific procedures, qualified-person training,
-- site-specific hazard assessment, or applicable safety requirements.
-- ============================================================================

begin;

create temporary table _seed_financial_literacy_l1_questions (
  question_number integer primary key,
  question_type text not null,
  difficulty text not null,
  prompt text not null,
  options jsonb not null,
  correct_answer jsonb not null,
  rationale text not null
);

insert into _seed_financial_literacy_l1_questions (
  question_number,
  question_type,
  difficulty,
  prompt,
  options,
  correct_answer,
  rationale
)
values
(1,'multiple_choice','foundational',
'What is gross pay?',
'[{"key":"A","text":"The amount earned before taxes and other deductions are taken out"},{"key":"B","text":"The amount deposited after all deductions"},{"key":"C","text":"Only overtime earnings"},{"key":"D","text":"The amount an employee owes in taxes"}]'::jsonb,
'["A"]'::jsonb,
'Gross pay is compensation earned before payroll deductions are applied.'),

(2,'multiple_choice','foundational',
'What is net pay?',
'[{"key":"A","text":"The amount an employee receives after taxes and other payroll deductions"},{"key":"B","text":"The hourly wage before deductions"},{"key":"C","text":"The total value of employer equipment"},{"key":"D","text":"Only the employee''s regular-time earnings"}]'::jsonb,
'["A"]'::jsonb,
'Net pay is the amount remaining after applicable deductions are taken from gross earnings.'),

(3,'multiple_choice','foundational',
'What is the main purpose of a personal budget?',
'[{"key":"A","text":"To plan how income will be used for expenses, savings, and other financial priorities"},{"key":"B","text":"To guarantee that income will increase"},{"key":"C","text":"To eliminate all taxes"},{"key":"D","text":"To calculate only work-related expenses"}]'::jsonb,
'["A"]'::jsonb,
'A budget helps a person plan and monitor how available income is allocated.'),

(4,'multiple_choice','foundational',
'What is a payroll deduction?',
'[{"key":"A","text":"An amount subtracted from gross pay for taxes, benefits, or other authorized purposes"},{"key":"B","text":"An additional payment for overtime"},{"key":"C","text":"A reimbursement for tools"},{"key":"D","text":"An increase in hourly wage"}]'::jsonb,
'["A"]'::jsonb,
'Payroll deductions are amounts removed from gross earnings for required or authorized purposes.'),

(5,'multiple_choice','foundational',
'Which statement BEST describes an emergency fund?',
'[{"key":"A","text":"Money set aside for unexpected necessary expenses or financial disruptions"},{"key":"B","text":"Money reserved only for entertainment"},{"key":"C","text":"A replacement for all insurance"},{"key":"D","text":"Money that must be spent before the end of each month"}]'::jsonb,
'["A"]'::jsonb,
'An emergency fund provides a financial cushion for unexpected needs or interruptions in income.'),

(6,'multiple_choice','foundational',
'What is interest?',
'[{"key":"A","text":"A cost paid for borrowing money or an amount earned on certain savings or investments"},{"key":"B","text":"A mandatory payroll tax"},{"key":"C","text":"A type of hourly wage"},{"key":"D","text":"A discount that always reduces a purchase price"}]'::jsonb,
'["A"]'::jsonb,
'Interest generally represents either the cost of borrowed money or earnings generated by certain financial accounts.'),

(7,'multiple_choice','foundational',
'What does an employer benefit typically refer to?',
'[{"key":"A","text":"Compensation or support provided in addition to direct wages, such as eligible insurance, retirement, or paid-leave programs"},{"key":"B","text":"Only an employee''s hourly wage"},{"key":"C","text":"Any tool owned by the employee"},{"key":"D","text":"A guaranteed annual bonus"}]'::jsonb,
'["A"]'::jsonb,
'Employee benefits are forms of compensation or support provided in addition to direct wages.'),

(8,'multiple_choice','foundational',
'Why is it important to review a pay statement?',
'[{"key":"A","text":"To confirm reported hours, earnings, deductions, and net pay appear accurate"},{"key":"B","text":"To determine what coworkers earn"},{"key":"C","text":"To change tax laws"},{"key":"D","text":"To avoid keeping personal financial records"}]'::jsonb,
'["A"]'::jsonb,
'Reviewing a pay statement helps an employee identify possible errors in hours, earnings, or deductions.'),

(9,'multiple_choice','application',
'An employee earns $20 per hour and works 40 regular hours. What is the employee''s gross regular pay before deductions?',
'[{"key":"A","text":"$800"},{"key":"B","text":"$600"},{"key":"C","text":"$400"},{"key":"D","text":"$1,200"}]'::jsonb,
'["A"]'::jsonb,
'Forty hours multiplied by $20 per hour equals $800 in gross regular earnings.'),

(10,'multiple_choice','application',
'A worker receives $900 in gross pay and has $180 in total deductions. What is the net pay?',
'[{"key":"A","text":"$720"},{"key":"B","text":"$1,080"},{"key":"C","text":"$900"},{"key":"D","text":"$180"}]'::jsonb,
'["A"]'::jsonb,
'Net pay is gross pay minus deductions: $900 minus $180 equals $720.'),

(11,'situational_judgment','application',
'A worker notices that the number of hours on a pay statement does not match the hours the worker recorded. What is the BEST response?',
'[{"key":"A","text":"Compare the records and report the possible discrepancy through the appropriate payroll or supervisor process"},{"key":"B","text":"Ignore it unless the difference is very large"},{"key":"C","text":"Change the worker''s personal record to match the pay statement"},{"key":"D","text":"Ask a coworker to reimburse the difference"}]'::jsonb,
'["A"]'::jsonb,
'Possible payroll errors should be checked against reliable records and raised through the appropriate workplace process.'),

(12,'multiple_choice','application',
'A worker has $2,400 in monthly take-home income. Fixed and necessary expenses total $2,050. How much remains before other spending or saving?',
'[{"key":"A","text":"$350"},{"key":"B","text":"$450"},{"key":"C","text":"$2,050"},{"key":"D","text":"$4,450"}]'::jsonb,
'["A"]'::jsonb,
'Subtracting $2,050 in expenses from $2,400 in income leaves $350.'),

(13,'situational_judgment','application',
'A worker receives a raise. What is a financially responsible FIRST step?',
'[{"key":"A","text":"Review the budget and decide how the additional income fits savings, expenses, debt, and other priorities"},{"key":"B","text":"Immediately increase recurring expenses by the full amount of the raise"},{"key":"C","text":"Stop reviewing pay statements"},{"key":"D","text":"Assume the entire raise will appear in net pay with no change in deductions"}]'::jsonb,
'["A"]'::jsonb,
'A change in compensation is a good reason to reassess the budget and financial priorities.'),

(14,'multiple_choice','application',
'A worker is comparing two job offers with different wages and benefits. What is the BEST approach?',
'[{"key":"A","text":"Compare the overall compensation package, including wages, expected hours, benefits, and relevant employee costs"},{"key":"B","text":"Compare only the hourly wage"},{"key":"C","text":"Choose the job with the longest commute"},{"key":"D","text":"Assume all benefit packages have the same value"}]'::jsonb,
'["A"]'::jsonb,
'Employment decisions are better informed by considering both direct wages and other meaningful compensation factors.'),

(15,'situational_judgment','application',
'A worker is considering borrowing money for a purchase. Which factor is MOST important to understand before agreeing?',
'[{"key":"A","text":"The repayment terms, interest, fees, and total expected cost"},{"key":"B","text":"Whether the paperwork is short"},{"key":"C","text":"Whether a coworker uses the same lender"},{"key":"D","text":"Whether the first payment can be delayed"}]'::jsonb,
'["A"]'::jsonb,
'Borrowing decisions should account for the full repayment obligation, not only the amount initially received.'),

(16,'multiple_choice','application',
'A worker wants to begin saving but has limited money left each month. Which approach BEST supports that goal?',
'[{"key":"A","text":"Choose a realistic recurring amount and include it as part of the monthly budget"},{"key":"B","text":"Wait until income is high enough that budgeting is unnecessary"},{"key":"C","text":"Spend all remaining money each month"},{"key":"D","text":"Use borrowed money as savings"}]'::jsonb,
'["A"]'::jsonb,
'Consistent, realistic saving can be incorporated into a budget even when the amount is modest.'),

(17,'scenario','scenario',
'A construction worker''s hours vary from week to week. The worker bases all monthly spending on the highest recent paycheck. What is the BEST improvement?',
'[{"key":"A","text":"Build the budget around a more conservative expected income and plan for fluctuations in hours"},{"key":"B","text":"Assume every future paycheck will match the highest one"},{"key":"C","text":"Use credit for all expenses during lower-hour weeks"},{"key":"D","text":"Stop tracking income because it changes"}]'::jsonb,
'["A"]'::jsonb,
'When income varies, conservative planning can reduce the risk of committing to expenses that cannot be supported during lower-income periods.'),

(18,'scenario','scenario',
'A worker is enrolling in employer benefits and does not understand the cost and coverage of several options. What is the BEST response?',
'[{"key":"A","text":"Review the plan information and ask the appropriate benefits or HR resource for clarification before making the selection"},{"key":"B","text":"Choose randomly because benefits are all equivalent"},{"key":"C","text":"Copy a coworker''s selections without reviewing them"},{"key":"D","text":"Decline every option without reading the information"}]'::jsonb,
'["A"]'::jsonb,
'Benefit choices can affect both compensation and personal costs, so employees should understand available information before selecting.'),

(19,'scenario','scenario',
'A worker receives an unexpected $700 vehicle-repair bill and has no money reserved for emergencies. Which financial lesson BEST applies?',
'[{"key":"A","text":"Regularly setting aside emergency savings can reduce the disruption caused by unexpected necessary expenses"},{"key":"B","text":"A budget should include only predictable entertainment expenses"},{"key":"C","text":"Unexpected expenses can always be ignored until the next year"},{"key":"D","text":"Emergency savings are useful only for people with fixed salaries"}]'::jsonb,
'["A"]'::jsonb,
'Emergency savings can provide a buffer when necessary expenses occur unexpectedly.'),

(20,'multiple_choice','scenario',
'Which behavior BEST demonstrates Level 1 proficiency in Financial Literacy?',
'[{"key":"A","text":"Ignoring pay information as long as money reaches the bank account"},{"key":"B","text":"Understanding basic pay, deductions, budgeting, saving, benefits, and borrowing concepts well enough to review routine financial information and ask for clarification when needed"},{"key":"C","text":"Making financial decisions based only on coworkers'' choices"},{"key":"D","text":"Assuming higher gross pay always means every expense is affordable"}]'::jsonb,
'["B"]'::jsonb,
'Level 1 proficiency means understanding and applying foundational financial concepts relevant to employment, compensation, budgeting, benefits, and career decisions.');


do $$
declare
  v_industry_id uuid;
  v_competency_id uuid := '925115ee-aaa6-404e-abdf-561c4af79bbf';
  v_construction_worker_role_id uuid := '0f5d7696-f36f-4413-b617-ee20f8c15a9f';
  v_assessment_id uuid;
  v_master_question_id uuid;
  v_assessment_question_id uuid;
  v_row record;
  v_level integer;
  v_role_template_id uuid;
  v_assessment_name text;
begin
  select i.id into v_industry_id
  from public.industries i
  where lower(i.slug) = 'construction'
     or lower(i.name) = 'construction'
  order by case when lower(i.slug) = 'construction' then 0 else 1 end
  limit 1;

  if v_industry_id is null then
    raise exception 'Construction industry not found';
  end if;

  if not exists (
    select 1
    from public.master_competency_templates c
    where c.id = v_competency_id
      and c.industry_id = v_industry_id
      and c.name = 'Financial Literacy'
      and c.is_current = true
  ) then
    raise exception 'Current Financial Literacy Master Competency not found';
  end if;



  if not exists (
    select 1
    from public.master_role_templates r
    join public.master_role_competency_requirements mrcr
      on mrcr.master_role_template_id = r.id
    where r.id = v_construction_worker_role_id
      and r.industry_id = v_industry_id
      and r.name = 'Construction Worker'
      and r.is_current = true
      and mrcr.master_competency_template_id = v_competency_id
      and mrcr.required_level = 1
  ) then
    raise exception 'Current Construction Worker L2 safety requirement not found';
  end if;



  if not exists (
    select 1
    from public.master_competency_assessment_standards s
    where s.master_competency_template_id = v_competency_id
      and s.target_level = 1
      and s.is_current = true
      and s.required_question_count = 20
      and s.foundational_count = 8
      and s.application_count = 8
      and s.scenario_count = 4
  ) then
    raise exception 'Expected current L1 assessment standard 20 / 8 / 8 / 4 not found';
  end if;

  -- ========================================================================
  -- Seed Level 1
  v_level := 1;
  v_role_template_id := '0f5d7696-f36f-4413-b617-ee20f8c15a9f'::uuid;
  v_assessment_name := 'Financial Literacy — Level 1 Competency Assessment';

  select a.id
  into v_assessment_id
  from public.assessments a
  where a.client_id is null
    and a.industry_id = v_industry_id
    and a.type = 'competency'
    and a.master_competency_template_id = v_competency_id
    and a.target_level = v_level
    and a.is_current = true
  order by a.version desc, a.name, a.id
  limit 1;

  if v_assessment_id is null then
    insert into public.assessments (
      client_id, industry_id, name, type,
      master_competency_template_id, target_level,
      version, is_current
    )
    values (
      null, v_industry_id, v_assessment_name, 'competency',
      v_competency_id, v_level,
      1, true
    )
    returning id into v_assessment_id;
  end if;

  for v_row in
    select * from _seed_financial_literacy_l1_questions
    order by question_number
  loop
    select q.id
    into v_master_question_id
    from public.master_question_bank q
    where q.industry_id = v_industry_id
      and q.master_competency_template_id = v_competency_id
      and q.prompt = v_row.prompt
      and q.is_current = true
    order by q.version desc, q.id
    limit 1;

    if v_master_question_id is null then
      insert into public.master_question_bank (
        industry_id,
        master_competency_template_id,
        domain,
        type,
        difficulty,
        prompt,
        options,
        points,
        critical_safety,
        practical_verification_required,
        status,
        version,
        is_current
      )
      values (
        v_industry_id,
        v_competency_id,
        'Financial Literacy',
        v_row.question_type,
        v_row.difficulty,
        v_row.prompt,
        v_row.options,
        1,
        false,
        false,
        'approved',
        1,
        true
      )
      returning id into v_master_question_id;
    end if;

    insert into public.master_question_answer_keys (
      master_question_id,
      correct_answer,
      scoring_notes,
      rationale
    )
    select
      v_master_question_id,
      v_row.correct_answer,
      'IntegrateU Financial Literacy L1 production assessment v1.0.',
      v_row.rationale
    where not exists (
      select 1
      from public.master_question_answer_keys k
      where k.master_question_id = v_master_question_id
    );

    insert into public.master_question_role_applicability (
      master_question_id,
      master_role_template_id
    )
    values (
      v_master_question_id,
      v_role_template_id
    )
    on conflict (
      master_question_id,
      master_role_template_id
    )
    do nothing;

    select aq.id
    into v_assessment_question_id
    from public.assessment_questions aq
    where aq.assessment_id = v_assessment_id
      and aq.source_master_question_id = v_master_question_id
    limit 1;

    if v_assessment_question_id is null then
      insert into public.assessment_questions (
        assessment_id,
        master_competency_template_id,
        type,
        prompt,
        scenario,
        image_url,
        options,
        points,
        sort_order,
        source_master_question_id,
        domain,
        difficulty,
        critical_safety,
        practical_verification_required
      )
      values (
        v_assessment_id,
        v_competency_id,
        v_row.question_type,
        v_row.prompt,
        null,
        null,
        v_row.options,
        1,
        v_row.question_number,
        v_master_question_id,
        'Financial Literacy',
        v_row.difficulty,
        false,
        false
      )
      returning id into v_assessment_question_id;
    end if;

    insert into public.assessment_question_answer_keys (
      question_id,
      correct_answer,
      scoring_notes
    )
    select
      v_assessment_question_id,
      v_row.correct_answer,
      concat_ws(
        E'\\n\\n',
        'IntegrateU Financial Literacy L1 production assessment v1.0.',
        'Rationale: ' || v_row.rationale
      )
    where not exists (
      select 1
      from public.assessment_question_answer_keys existing_key
      where existing_key.question_id = v_assessment_question_id
    );
  end loop;

end;
$$;

commit;

-- ============================================================================
-- VERIFICATION 1 — ASSESSMENT CONTENT
-- ============================================================================

select
  a.target_level,
  a.id as assessment_id,
  a.name as assessment_name,
  count(distinct aq.id)::integer as question_count,
  count(distinct ak.question_id)::integer as answer_key_count,
  count(distinct aq.id) filter (
    where aq.difficulty = 'foundational'
  )::integer as foundational_count,
  count(distinct aq.id) filter (
    where aq.difficulty = 'application'
  )::integer as application_count,
  count(distinct aq.id) filter (
    where aq.difficulty = 'scenario'
  )::integer as scenario_count,
  count(distinct aq.id) filter (
    where aq.critical_safety
  )::integer as critical_safety_count,
  count(distinct aq.id) filter (
    where aq.practical_verification_required
  )::integer as practical_verification_required_count
from public.assessments a
left join public.assessment_questions aq
  on aq.assessment_id = a.id
 and aq.master_competency_template_id =
   '925115ee-aaa6-404e-abdf-561c4af79bbf'::uuid
 and aq.source_master_question_id is not null
left join public.assessment_question_answer_keys ak
  on ak.question_id = aq.id
where a.client_id is null
  and a.is_current = true
  and a.type = 'competency'
  and a.master_competency_template_id =
    '925115ee-aaa6-404e-abdf-561c4af79bbf'::uuid
  and a.target_level = 1
group by a.id, a.target_level, a.name;


-- ============================================================================
-- VERIFICATION 2 — ROLE APPLICABILITY
-- ============================================================================

with q as (
  select
    a.target_level,
    aq.source_master_question_id
  from public.assessments a
  join public.assessment_questions aq
    on aq.assessment_id = a.id
   and aq.source_master_question_id is not null
  where a.client_id is null
    and a.is_current = true
    and a.type = 'competency'
    and a.master_competency_template_id =
      '925115ee-aaa6-404e-abdf-561c4af79bbf'::uuid
    and a.target_level = 1
)
select
  q.target_level,
  count(distinct ra.master_question_id)::integer
    as role_applicability_count
from q
join public.master_question_role_applicability ra
  on ra.master_question_id = q.source_master_question_id
where ra.master_role_template_id =
  '0f5d7696-f36f-4413-b617-ee20f8c15a9f'::uuid
group by q.target_level;
